package com.experis.de.MeFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import org.hibernate.annotations.Type;

import javax.persistence.*;

@Entity
@Table(name = "Profile")
@Schema(description = "Profile Model")
public @Data class Profile {

    //autogenerated ID
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    private Integer age;
    private Integer weight;
    private Integer height;
    private Integer fitnessLevel;
    private Integer trainingFrequency;
    private Boolean contributorRequest;

    @Lob
    // ImageType needed for saving "big" data stream
    // see: https://stackoverflow.com/questions/3164072/large-objects-may-not-be-used-in-auto-commit-mode
    @Type(type = "org.hibernate.type.ImageType")
    private byte[] picture;

    @OneToOne(mappedBy = "profile")
    private User user;

    @JsonGetter("user")
    public String userGetter() {
        if (user != null)
            return "/api/v1/users/" + user.getId();
        else
            return null;
    }

    /*
    @JsonGetter("goal")
    public String goalGetter() {
        if (goal != null)
            return "/api/v1/goals/" + goal.getId();
        else
            return null;
    }
    */
}
